plugins:
  - rubocop-performance
  - rubocop-rails
  - rubocop-erb
  - rubocop-rspec
  - rubocop-rspec_rails
  - rubocop-factory_bot

AllCops:
  NewCops: enable

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Exclude:
    - app/views/**/*

Rails/I18nLocaleTexts:
  Enabled: false

Metrics/MethodLength:
  Max: 20
  Exclude:
    - db/migrate/**/*.rb

Metrics/AbcSize:
  Max: 40
  Exclude:
    - db/migrate/**/*.rb

RSpec/MultipleExpectations:
  Enabled: false

RSpec/NestedGroups:
  Max: 5

Metrics/BlockLength:
  Exclude:
    - config/environments/*.rb
